name: skills_first_test
run-name: verifying_order
on:
  push:
    branches:
      - main

jobs:
  build-hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Message
        run: echo "Hello world!"
